# This is based on the empress github actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.6"]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: catvae
          python-version: ${{ matrix.python-version }}

      - name: Test conda installation
        shell: bash -l {0}
        run: conda info

      - name: Install conda packages
        shell: bash -l {0}
        run: conda install pytorch pytorch-lightning gneiss scikit-bio biom-format pandas scipy numpy numba pycodestyle flake8 -c pytorch -c conda-forge -c bioconda

      - name: Install pip packages
        shell: bash -l {0}
        run: pip install geotorch

      - name: Install catvae
        shell: bash -l {0}
        run: pip install -e .[dev]

      - name: Run tests
        shell: bash -l {0}
        run: make all
